//@ pragma UseQApplication
import QtQuick
import Quickshell
import Quickshell.Io
import Quickshell.Widgets
import Quickshell.Hyprland
import Quickshell.Services.SystemTray
import Quickshell.Services.UPower
import Quickshell.Services.Pipewire
import Quickshell.Networking

// Quickshell bar, run alongside/instead of waybar (module.quickshell.enable).
// "Islands" layout: separate floating pill clusters instead of one continuous
// strip. UseQApplication above is required for SystemTrayItem.display() (the
// native right-click/menu-only popup) to work at all - without it quickshell
// throws "Cannot display PlatformMenuEntry ... not started in QApplication
// mode" and every menu-only tray click silently does nothing.

ShellRoot {
  id: root

  // A small colored pill with centered text - the "module chip" look from
  // the original waybar css (each widget gets its own background color).
  component Chip: Rectangle {
    property alias label: chipText.text
    property color fg: "#181825"
    radius: 8
    implicitHeight: 26
    implicitWidth: chipText.implicitWidth + 16
    height: implicitHeight
    width: implicitWidth

    Text {
      id: chipText
      anchors.centerIn: parent
      color: parent.fg
      font.pixelSize: 13
    }
  }

  // ---------------------------------------------------------------------
  // Workspace data, generated by the nix module from module.workspaces.entries.
  // This is the full, authoritative list of workspaces - always rendered as
  // buttons regardless of whether Hyprland currently has them instantiated
  // (Hyprland only creates a workspace object once something is on it).
  // ---------------------------------------------------------------------
  FileView {
    id: workspaceFile
    path: Qt.resolvedUrl("./workspaces.json")
    watchChanges: true
    onFileChanged: reload()

    JsonAdapter {
      id: workspaceData
      property var entries: []
    }
  }

  function focusedWorkspaceId() {
    return Hyprland.focusedWorkspace ? Hyprland.focusedWorkspace.id : -1;
  }

  function focusWorkspace(id) {
    focusProc.command = [
      "hyprctl", "dispatch",
      `hl.dsp.focus({workspace = ${id}, on_current_monitor = true})`
    ];
    focusProc.running = true;
  }

  Process { id: focusProc }
  Process { id: powerProc; command: ["wlogout", "-b", "4"] }

  // ---------------------------------------------------------------------
  // Notifications (swaync) - "-swb" is a long-running subscription that
  // prints one JSON line per state change, not a one-shot query.
  // ---------------------------------------------------------------------
  property string notifIcon: ""
  property string notifTooltip: ""

  readonly property var notifIconMap: ({
    "notification": "",
    "none": "",
    "dnd-notification": "",
    "dnd-none": "",
    "inhibited-notification": "",
    "inhibited-none": "",
    "dnd-inhibited-notification": "",
    "dnd-inhibited-none": ""
  })

  Process {
    id: notifWatch
    command: ["swaync-client", "-swb"]
    running: true
    stdout: SplitParser {
      splitMarker: "\n"
      onRead: (line) => {
        if (!line) return;
        try {
          const data = JSON.parse(line);
          notifIcon = notifIconMap[data.alt] ?? notifIconMap["none"];
          notifTooltip = data.tooltip ?? "";
        } catch (e) {}
      }
    }
  }

  Process { id: notifToggle; command: ["swaync-client", "-t", "-sw"] }
  Process { id: notifDismiss; command: ["swaync-client", "-d", "-sw"] }

  // ---------------------------------------------------------------------
  // CPU / memory, read straight from /proc - quickshell has no built-in
  // service for either (unlike battery/audio/network below).
  // ---------------------------------------------------------------------
  property real cpuPrevIdle: -1
  property real cpuPrevTotal: -1
  property int cpuUsage: 0

  FileView {
    id: cpuFile
    path: "/proc/stat"
    blockLoading: true
    onLoaded: {
      const line = text().split("\n")[0];
      const parts = line.trim().split(/\s+/).slice(1).map(Number);
      const idle = parts[3] + (parts[4] || 0);
      const total = parts.reduce((a, b) => a + b, 0);
      if (cpuPrevTotal >= 0) {
        const totalDelta = total - cpuPrevTotal;
        const idleDelta = idle - cpuPrevIdle;
        cpuUsage = totalDelta > 0 ? Math.round(100 * (1 - idleDelta / totalDelta)) : 0;
      }
      cpuPrevTotal = total;
      cpuPrevIdle = idle;
    }
  }
  Timer { interval: 2000; running: true; repeat: true; triggeredOnStart: true; onTriggered: cpuFile.reload() }

  property real memUsedGb: 0

  FileView {
    id: memFile
    path: "/proc/meminfo"
    blockLoading: true
    onLoaded: {
      const lines = text().split("\n");
      let totalKb = 0, availKb = 0;
      for (const l of lines) {
        if (l.startsWith("MemTotal:")) totalKb = parseInt(l.split(/\s+/)[1]);
        else if (l.startsWith("MemAvailable:")) availKb = parseInt(l.split(/\s+/)[1]);
      }
      memUsedGb = (totalKb - availKb) / 1024 / 1024;
    }
  }
  Timer { interval: 5000; running: true; repeat: true; triggeredOnStart: true; onTriggered: memFile.reload() }

  // ---------------------------------------------------------------------
  // Pipewire needs the default sink referenced through a PwObjectTracker
  // for its properties (volume/muted) to actually stay live-bound.
  // ---------------------------------------------------------------------
  PwObjectTracker {
    objects: Pipewire.defaultAudioSink ? [Pipewire.defaultAudioSink] : []
  }

  function connectedNetworkDevice() {
    const devices = Networking.devices.values;
    for (let i = 0; i < devices.length; i++) if (devices[i].connected) return devices[i];
    return null;
  }
  function connectedNetwork(device) {
    if (!device) return null;
    const nets = device.networks.values;
    for (let i = 0; i < nets.length; i++) if (nets[i].connected) return nets[i];
    return null;
  }

  // One bar per connected monitor, not just whichever one quickshell
  // treats as primary.
  Variants {
    model: Quickshell.screens

    PanelWindow {
      id: bar
      screen: modelData
      anchors { left: true; right: true; top: true }
      implicitHeight: 50
      color: "transparent"

    // ---------------- clock island ----------------
    WrapperRectangle {
      id: clockIsland
      anchors.left: parent.left
      anchors.leftMargin: 10
      anchors.verticalCenter: parent.verticalCenter
      margin: 10
      radius: 16
      color: "#181825"

      Chip {
        color: "#cdd6f4"
        label: Qt.formatDateTime(new Date(), "ddd dd MMM  HH:mm")

        Timer {
          interval: 1000
          running: true
          repeat: true
          onTriggered: parent.label = Qt.formatDateTime(new Date(), "ddd dd MMM  HH:mm")
        }
      }
    }

    // ---------------- tray island ----------------
    WrapperRectangle {
      anchors.left: clockIsland.right
      anchors.leftMargin: 10
      anchors.verticalCenter: parent.verticalCenter
      margin: 10
      radius: 16
      color: "#181825"

      Row {
        spacing: 10
        Repeater {
          model: SystemTray.items
          delegate: Rectangle {
            width: 30
            height: 30
            radius: 8
            color: "#404A60"

            Image {
              anchors.centerIn: parent
              width: 18
              height: 18
              source: modelData.icon
            }

            MouseArea {
              anchors.fill: parent
              acceptedButtons: Qt.LeftButton | Qt.RightButton
              onClicked: (mouse) => {
                if (mouse.button === Qt.RightButton) {
                  if (modelData.hasMenu) modelData.display(bar, mouse.x, mouse.y);
                  else modelData.secondaryActivate();
                } else {
                  if (modelData.onlyMenu && modelData.hasMenu) modelData.display(bar, mouse.x, mouse.y);
                  else modelData.activate();
                }
              }
            }
          }
        }
      }
    }

    // ---------------- center island: notification + workspaces + power ----------------
    WrapperRectangle {
      anchors.horizontalCenter: parent.horizontalCenter
      anchors.verticalCenter: parent.verticalCenter
      margin: 10
      radius: 16
      color: "#181825"

      Row {
        spacing: 10

        Rectangle {
          width: 34
          height: 34
          radius: 10
          color: "#DDC062"
          anchors.verticalCenter: parent.verticalCenter

          Text {
            anchors.centerIn: parent
            text: notifIcon
            color: "#181825"
            font.pixelSize: 18
          }

          MouseArea {
            anchors.fill: parent
            acceptedButtons: Qt.LeftButton | Qt.RightButton
            onClicked: (mouse) => {
              if (mouse.button === Qt.RightButton) notifDismiss.running = true;
              else notifToggle.running = true;
            }
          }
        }

        Row {
          spacing: 8
          anchors.verticalCenter: parent.verticalCenter

          Repeater {
            model: workspaceData.entries
            delegate: Rectangle {
              readonly property bool focused: modelData.id === focusedWorkspaceId()
              width: 42
              height: 36
              radius: 12
              color: focused ? "#cdd6f4" : "#404A60"

              Text {
                anchors.centerIn: parent
                text: modelData.icon
                font.pixelSize: 20
                color: focused ? "#181825" : "#D8DEE9"
              }

              MouseArea {
                anchors.fill: parent
                onClicked: focusWorkspace(modelData.id)
              }
            }
          }
        }

        Rectangle {
          width: 34
          height: 34
          radius: 10
          color: "#f38ba8"
          anchors.verticalCenter: parent.verticalCenter

          Text {
            anchors.centerIn: parent
            text: "⏻"
            color: "#181825"
            font.pixelSize: 16
          }

          MouseArea {
            anchors.fill: parent
            onClicked: powerProc.running = true
          }
        }
      }
    }

    // ---------------- right island: network, audio, cpu, memory, battery ----------------
    WrapperRectangle {
      anchors.right: parent.right
      anchors.rightMargin: 10
      anchors.verticalCenter: parent.verticalCenter
      margin: 10
      radius: 16
      color: "#181825"

      Row {
        spacing: 8

        Chip {
          color: "#A3BE8C"
          readonly property var device: connectedNetworkDevice()
          readonly property var net: connectedNetwork(device)
          label: {
            if (!device) return " Disconnected";
            if (device.type === DeviceType.Wifi) return "󰤨 " + (net ? net.name : device.name);
            return "󰅢 " + device.name;
          }
        }

        Chip {
          id: audioChip
          color: "#89dceb"
          readonly property var sink: Pipewire.defaultAudioSink
          label: {
            if (!sink || !sink.audio) return "--";
            const pct = Math.round(sink.audio.volume * 100);
            return sink.audio.muted ? "󰖁" : "" + pct + "%";
          }

          MouseArea {
            anchors.fill: parent
            onClicked: {
              const sink = Pipewire.defaultAudioSink;
              if (sink && sink.audio) sink.audio.muted = !sink.audio.muted;
            }
          }
        }

        Chip {
          color: "#FF7B87"
          label: " " + cpuUsage + "%"
        }

        Chip {
          color: "#FF9F81"
          label: " " + memUsedGb.toFixed(1) + "G"
        }

        Chip {
          color: "#cba6f7"
          readonly property var battery: UPower.displayDevice
          visible: battery && battery.isPresent
          label: {
            if (!battery || !battery.isPresent) return "";
            const icons = ["󰂎", "󰁼", "󰁿", "󰂁", "󰁹"];
            const pct = Math.round(battery.percentage * 100);
            const tier = Math.max(0, Math.min(icons.length - 1, Math.floor(pct / 25)));
            const charging = battery.state === UPowerDeviceState.Charging;
            return icons[tier] + (charging ? "󱐋" : "") + pct + "%";
          }
        }
      }
    }
    }
  }
}
