import QtQuick
import Quickshell
import Quickshell.Io
import Quickshell.Widgets
import Quickshell.Hyprland
import Quickshell.Services.SystemTray
import Quickshell.Services.UPower
import Quickshell.Services.Pipewire
import Quickshell.Networking

// Quickshell bar, run alongside/instead of waybar (module.quickshell.enable).
// "Islands" layout: three separate floating pill clusters instead of one
// continuous strip. Widgets deliberately mirror modules/waybar's layout and
// icon set 1:1 so switching between the two bars feels the same.

ShellRoot {
  id: root

  // ---------------------------------------------------------------------
  // Workspace data, generated by the nix module from module.workspaces.entries
  // ---------------------------------------------------------------------
  FileView {
    id: workspaceFile
    path: Qt.resolvedUrl("./workspaces.json")
    watchChanges: true
    onFileChanged: reload()

    JsonAdapter {
      id: workspaceData
      property var entries: []
    }
  }

  function workspaceIcon(id) {
    const entries = workspaceData.entries;
    for (let i = 0; i < entries.length; i++) {
      if (entries[i].id === id) return entries[i].icon;
      if (entries[i].id + 1 === id) return entries[i].shiftedIcon;
    }
    return "";
  }

  function focusWorkspace(id) {
    focusProc.command = [
      "hyprctl", "dispatch",
      `hl.dsp.focus({workspace = ${id}, on_current_monitor = true})`
    ];
    focusProc.running = true;
  }

  Process { id: focusProc }
  Process { id: powerProc; command: ["wlogout", "-b", "4"] }

  // ---------------------------------------------------------------------
  // Notifications (swaync) - "-swb" is a long-running subscription that
  // prints one JSON line per state change, not a one-shot query.
  // ---------------------------------------------------------------------
  property string notifIcon: ""
  property string notifTooltip: ""

  readonly property var notifIconMap: ({
    "notification": "",
    "none": "",
    "dnd-notification": "",
    "dnd-none": "",
    "inhibited-notification": "",
    "inhibited-none": "",
    "dnd-inhibited-notification": "",
    "dnd-inhibited-none": ""
  })

  Process {
    id: notifWatch
    command: ["swaync-client", "-swb"]
    running: true
    stdout: SplitParser {
      splitMarker: "\n"
      onRead: (line) => {
        if (!line) return;
        try {
          const data = JSON.parse(line);
          notifIcon = notifIconMap[data.alt] ?? notifIconMap["none"];
          notifTooltip = data.tooltip ?? "";
        } catch (e) {}
      }
    }
  }

  Process { id: notifToggle; command: ["swaync-client", "-t", "-sw"] }
  Process { id: notifDismiss; command: ["swaync-client", "-d", "-sw"] }

  // ---------------------------------------------------------------------
  // CPU / memory, read straight from /proc - quickshell has no built-in
  // service for either (unlike battery/audio/network below).
  // ---------------------------------------------------------------------
  property real cpuPrevIdle: -1
  property real cpuPrevTotal: -1
  property int cpuUsage: 0

  FileView {
    id: cpuFile
    path: "/proc/stat"
    blockLoading: true
    onLoaded: {
      const line = text().split("\n")[0];
      const parts = line.trim().split(/\s+/).slice(1).map(Number);
      const idle = parts[3] + (parts[4] || 0);
      const total = parts.reduce((a, b) => a + b, 0);
      if (cpuPrevTotal >= 0) {
        const totalDelta = total - cpuPrevTotal;
        const idleDelta = idle - cpuPrevIdle;
        cpuUsage = totalDelta > 0 ? Math.round(100 * (1 - idleDelta / totalDelta)) : 0;
      }
      cpuPrevTotal = total;
      cpuPrevIdle = idle;
    }
  }
  Timer { interval: 2000; running: true; repeat: true; triggeredOnStart: true; onTriggered: cpuFile.reload() }

  property real memUsedGb: 0

  FileView {
    id: memFile
    path: "/proc/meminfo"
    blockLoading: true
    onLoaded: {
      const lines = text().split("\n");
      let totalKb = 0, availKb = 0;
      for (const l of lines) {
        if (l.startsWith("MemTotal:")) totalKb = parseInt(l.split(/\s+/)[1]);
        else if (l.startsWith("MemAvailable:")) availKb = parseInt(l.split(/\s+/)[1]);
      }
      memUsedGb = (totalKb - availKb) / 1024 / 1024;
    }
  }
  Timer { interval: 5000; running: true; repeat: true; triggeredOnStart: true; onTriggered: memFile.reload() }

  // ---------------------------------------------------------------------
  // Pipewire needs the default sink referenced through a PwObjectTracker
  // for its properties (volume/muted) to actually stay live-bound.
  // ---------------------------------------------------------------------
  PwObjectTracker {
    objects: Pipewire.defaultAudioSink ? [Pipewire.defaultAudioSink] : []
  }

  function connectedNetworkDevice() {
    const devices = Networking.devices.values;
    for (let i = 0; i < devices.length; i++) if (devices[i].connected) return devices[i];
    return null;
  }
  function connectedNetwork(device) {
    if (!device) return null;
    const nets = device.networks.values;
    for (let i = 0; i < nets.length; i++) if (nets[i].connected) return nets[i];
    return null;
  }

  PanelWindow {
    id: bar
    anchors { left: true; right: true; top: true }
    implicitHeight: 48
    color: "transparent"

    // ---------------- LEFT island: clock + tray ----------------
    WrapperRectangle {
      anchors.left: parent.left
      anchors.leftMargin: 10
      anchors.verticalCenter: parent.verticalCenter
      margin: 8
      radius: 14
      color: "#181825"

      Row {
        spacing: 12

        Text {
          id: clock
          color: "#cdd6f4"
          font.bold: true
          font.pixelSize: 15
          text: Qt.formatDateTime(new Date(), "ddd dd MMM  HH:mm")

          Timer {
            interval: 1000
            running: true
            repeat: true
            onTriggered: clock.text = Qt.formatDateTime(new Date(), "ddd dd MMM  HH:mm")
          }
        }

        Row {
          spacing: 8
          Repeater {
            model: SystemTray.items
            delegate: Image {
              width: 20
              height: 20
              source: modelData.icon

              MouseArea {
                anchors.fill: parent
                acceptedButtons: Qt.LeftButton | Qt.RightButton
                onClicked: (mouse) => {
                  if (mouse.button === Qt.RightButton) {
                    if (modelData.hasMenu) modelData.display(bar, mouse.x, mouse.y);
                    else modelData.secondaryActivate();
                  } else {
                    if (modelData.onlyMenu && modelData.hasMenu) modelData.display(bar, mouse.x, mouse.y);
                    else modelData.activate();
                  }
                }
              }
            }
          }
        }
      }
    }

    // ---------------- CENTER island: notification + workspaces + power ----------------
    WrapperRectangle {
      anchors.horizontalCenter: parent.horizontalCenter
      anchors.verticalCenter: parent.verticalCenter
      margin: 8
      radius: 14
      color: "#181825"

      Row {
        spacing: 16

        Text {
          text: notifIcon
          color: "#f9e2af"
          font.pixelSize: 18
          anchors.verticalCenter: parent.verticalCenter

          MouseArea {
            anchors.fill: parent
            acceptedButtons: Qt.LeftButton | Qt.RightButton
            onClicked: (mouse) => {
              if (mouse.button === Qt.RightButton) notifDismiss.running = true;
              else notifToggle.running = true;
            }
          }
        }

        Row {
          spacing: 8
          anchors.verticalCenter: parent.verticalCenter

          Repeater {
            model: Hyprland.workspaces
            delegate: Rectangle {
              readonly property bool focused: modelData.focused
              width: 40
              height: 34
              radius: 12
              color: focused ? "#cdd6f4" : "#404A60"

              Text {
                anchors.centerIn: parent
                text: workspaceIcon(modelData.id)
                font.pixelSize: 20
                color: focused ? "#181825" : "#D8DEE9"
              }

              MouseArea {
                anchors.fill: parent
                onClicked: focusWorkspace(modelData.id)
              }
            }
          }
        }

        Rectangle {
          width: 34
          height: 34
          radius: 12
          color: "#f38ba8"
          anchors.verticalCenter: parent.verticalCenter

          Text {
            anchors.centerIn: parent
            text: "⏻"
            color: "#181825"
            font.pixelSize: 16
          }

          MouseArea {
            anchors.fill: parent
            onClicked: powerProc.running = true
          }
        }
      }
    }

    // ---------------- RIGHT island: network, audio, cpu, memory, battery ----------------
    WrapperRectangle {
      anchors.right: parent.right
      anchors.rightMargin: 10
      anchors.verticalCenter: parent.verticalCenter
      margin: 8
      radius: 14
      color: "#181825"

      Row {
        spacing: 16

        Text {
          id: networkText
          color: "#A3BE8C"
          font.pixelSize: 14
          anchors.verticalCenter: parent.verticalCenter
          readonly property var device: connectedNetworkDevice()
          readonly property var net: connectedNetwork(device)
          text: {
            if (!device) return " Disconnected";
            if (device.type === DeviceType.Wifi) return "󰤨 " + (net ? net.name : device.name);
            return "󰅢 " + device.name;
          }
        }

        Text {
          id: audioText
          color: "#89dceb"
          font.pixelSize: 14
          anchors.verticalCenter: parent.verticalCenter
          readonly property var sink: Pipewire.defaultAudioSink
          text: {
            if (!sink || !sink.audio) return "--";
            const pct = Math.round(sink.audio.volume * 100);
            return sink.audio.muted ? "󰖁" : "" + pct + "%";
          }

          MouseArea {
            anchors.fill: parent
            onClicked: {
              const sink = Pipewire.defaultAudioSink;
              if (sink && sink.audio) sink.audio.muted = !sink.audio.muted;
            }
          }
        }

        Text {
          color: "#FF7B87"
          font.pixelSize: 14
          anchors.verticalCenter: parent.verticalCenter
          text: "  " + cpuUsage + "%"
        }

        Text {
          color: "#FF9F81"
          font.pixelSize: 14
          anchors.verticalCenter: parent.verticalCenter
          text: "  " + memUsedGb.toFixed(1) + "G"
        }

        Text {
          color: "#cba6f7"
          font.pixelSize: 14
          anchors.verticalCenter: parent.verticalCenter
          readonly property var battery: UPower.displayDevice
          visible: battery && battery.isPresent
          text: {
            if (!battery || !battery.isPresent) return "";
            const icons = ["󰂎", "󰁼", "󰁿", "󰂁", "󰁹"];
            const pct = Math.round(battery.percentage * 100);
            const tier = Math.max(0, Math.min(icons.length - 1, Math.floor(pct / 25)));
            const charging = battery.state === UPowerDeviceState.Charging;
            return icons[tier] + (charging ? "󱐋" : "") + pct + "%";
          }
        }
      }
    }
  }
}
