//@ pragma UseQApplication
import QtQuick
import Quickshell
import Quickshell.Io
import Quickshell.Widgets
import Quickshell.Hyprland
import Quickshell.Services.SystemTray
import Quickshell.Services.UPower
import Quickshell.Services.Pipewire
import Quickshell.Networking

// Quickshell bar, run alongside/instead of waybar (module.quickshell.enable).
// "Islands" layout: separate floating pill clusters instead of one continuous
// strip. UseQApplication above is required for tray context menus (QsMenuAnchor)
// to render at all - without it quickshell throws "Cannot display
// PlatformMenuEntry ... not started in QApplication mode" and every
// menu-only tray click silently does nothing. The menu is a native Qt
// platform popup, so it follows the Qt platform theme, not this file's
// colors - it won't be dark-themed unless Qt itself is configured for it.

ShellRoot {
  id: root

  // Muted, mostly-monochrome palette (one accent color, used sparingly)
  // instead of the earlier per-widget rainbow of pastel accents.
  readonly property color islandBg: "#181825"
  readonly property color chipBg: "#22222c"
  readonly property color textColor: "#d8d8e2"
  readonly property color mutedTextColor: "#9a9aab"
  readonly property color accentColor: "#6c7ce0"
  // Every island is pinned to this height so they line up regardless of
  // what their tallest child happens to be (was previously auto-sized per
  // island from content, which made them visibly uneven heights).
  readonly property int islandHeight: 40

  // Flat colored text, no background pill - just a plain Text with a
  // `label` alias so call sites read the same as before.
  component Chip: Text {
    id: chipRoot
    property alias label: chipRoot.text
    // Hardcoded rather than referencing root.textColor: inline `component`
    // bodies are their own scope and qmllint flags outer-id references from
    // inside one as unresolved - given a past instance this session of an
    // "unqualified"-flagged reference turning out to be a genuine runtime
    // ReferenceError (PanelWindow.anchors), not risking it here too.
    color: "#d8d8e2"
    font.pixelSize: 14
    anchors.verticalCenter: parent.verticalCenter
  }

  // ---------------------------------------------------------------------
  // Workspace data, generated by the nix module from module.workspaces.entries.
  // This is the full, authoritative list of workspaces - always rendered as
  // buttons regardless of whether Hyprland currently has them instantiated
  // (Hyprland only creates a workspace object once something is on it).
  // ---------------------------------------------------------------------
  FileView {
    id: workspaceFile
    path: Qt.resolvedUrl("./workspaces.json")
    watchChanges: true
    onFileChanged: reload()

    JsonAdapter {
      id: workspaceData
      property var entries: []
    }
  }

  // Store paths for the exact scripts modules/waybar's custom/task-workspaces
  // widget already runs - reused rather than re-derived here.
  FileView {
    id: scriptsFile
    path: Qt.resolvedUrl("./scripts.json")
    watchChanges: true
    onFileChanged: reload()

    JsonAdapter {
      id: scriptsData
      property string taskStatus: ""
      property string taskPicker: ""
    }
  }

  function focusedWorkspaceId() {
    return Hyprland.focusedWorkspace ? Hyprland.focusedWorkspace.id : -1;
  }

  // Static workspaces (module.workspaces.entries) always show, even empty.
  // A shifted (+1) workspace shows too, but only while it exists. Task
  // workspaces (id >= 200, see task-workspace-scripts.nix's reserved id
  // space) are deliberately excluded here - they get their own "Tasks: N"
  // island instead of cluttering this row.
  function mergedWorkspaceIds() {
    const ids = workspaceData.entries.map(e => e.id);
    const seen = new Set(ids);
    for (const w of Hyprland.workspaces.values) {
      if (w.id < 200 && !seen.has(w.id)) {
        seen.add(w.id);
        ids.push(w.id);
      }
    }
    ids.sort((a, b) => a - b);
    return ids;
  }

  function workspaceIcon(id) {
    for (const e of workspaceData.entries) {
      if (e.id === id) return e.icon;
      if (e.id + 1 === id) return e.shiftedIcon;
    }
    return "";
  }

  // Count of currently-active (running) task workspaces, from the same
  // space-separated icon string modules/waybar's custom/task-workspaces
  // widget renders directly - here we only need how many, not which.
  function activeTaskCount() {
    const trimmed = taskStatusText.trim();
    return trimmed.length === 0 ? 0 : trimmed.split(/\s+/).length;
  }

  function focusWorkspace(id) {
    focusProc.command = [
      "hyprctl", "dispatch",
      `hl.dsp.focus({workspace = ${id}, on_current_monitor = true})`
    ];
    focusProc.running = true;
  }

  Process { id: focusProc }

  // Session/logout screen (SessionScreen.qml) replaces wlogout for the
  // power button - single instance, not per-monitor.
  SessionScreen { id: sessionScreen }

  // Task-workspaces widget (waybar's custom/task-workspaces): icons of
  // currently-active predefined/ad-hoc tasks, polled every 3s same as waybar.
  property string taskStatusText: ""
  property string taskStatusTooltip: ""

  Process {
    id: taskStatusProc
    command: scriptsData.taskStatus ? [scriptsData.taskStatus] : []
    stdout: StdioCollector {
      onStreamFinished: {
        try {
          const data = JSON.parse(this.text);
          taskStatusText = data.text ?? "";
          taskStatusTooltip = data.tooltip ?? "";
        } catch (e) {}
      }
    }
  }
  Timer {
    interval: 3000
    running: scriptsData.taskStatus !== ""
    repeat: true
    triggeredOnStart: true
    onTriggered: if (!taskStatusProc.running) taskStatusProc.running = true
  }
  Process { id: taskPickerProc; command: scriptsData.taskPicker ? [scriptsData.taskPicker] : [] }

  // ---------------------------------------------------------------------
  // Notifications (swaync) - "-swb" is a long-running subscription that
  // prints one JSON line per state change, not a one-shot query.
  // ---------------------------------------------------------------------
  property string notifIcon: ""
  property string notifTooltip: ""

  readonly property var notifIconMap: ({
    "notification": "",
    "none": "",
    "dnd-notification": "",
    "dnd-none": "",
    "inhibited-notification": "",
    "inhibited-none": "",
    "dnd-inhibited-notification": "",
    "dnd-inhibited-none": ""
  })

  Process {
    id: notifWatch
    command: ["swaync-client", "-swb"]
    running: true
    stdout: SplitParser {
      splitMarker: "\n"
      onRead: (line) => {
        if (!line) return;
        try {
          const data = JSON.parse(line);
          notifIcon = notifIconMap[data.alt] ?? notifIconMap["none"];
          notifTooltip = data.tooltip ?? "";
        } catch (e) {}
      }
    }
  }

  Process { id: notifToggle; command: ["swaync-client", "-t", "-sw"] }
  Process { id: notifDismiss; command: ["swaync-client", "-d", "-sw"] }

  // ---------------------------------------------------------------------
  // CPU / memory, read straight from /proc - quickshell has no built-in
  // service for either (unlike battery/audio/network below).
  // ---------------------------------------------------------------------
  property real cpuPrevIdle: -1
  property real cpuPrevTotal: -1
  property int cpuUsage: 0

  FileView {
    id: cpuFile
    path: "/proc/stat"
    blockLoading: true
    onLoaded: {
      const line = text().split("\n")[0];
      const parts = line.trim().split(/\s+/).slice(1).map(Number);
      const idle = parts[3] + (parts[4] || 0);
      const total = parts.reduce((a, b) => a + b, 0);
      if (cpuPrevTotal >= 0) {
        const totalDelta = total - cpuPrevTotal;
        const idleDelta = idle - cpuPrevIdle;
        cpuUsage = totalDelta > 0 ? Math.round(100 * (1 - idleDelta / totalDelta)) : 0;
      }
      cpuPrevTotal = total;
      cpuPrevIdle = idle;
    }
  }
  Timer { interval: 2000; running: true; repeat: true; triggeredOnStart: true; onTriggered: cpuFile.reload() }

  property real memUsedGb: 0

  FileView {
    id: memFile
    path: "/proc/meminfo"
    blockLoading: true
    onLoaded: {
      const lines = text().split("\n");
      let totalKb = 0, availKb = 0;
      for (const l of lines) {
        if (l.startsWith("MemTotal:")) totalKb = parseInt(l.split(/\s+/)[1]);
        else if (l.startsWith("MemAvailable:")) availKb = parseInt(l.split(/\s+/)[1]);
      }
      memUsedGb = (totalKb - availKb) / 1024 / 1024;
    }
  }
  Timer { interval: 5000; running: true; repeat: true; triggeredOnStart: true; onTriggered: memFile.reload() }

  // ---------------------------------------------------------------------
  // Pipewire needs the default sink referenced through a PwObjectTracker
  // for its properties (volume/muted) to actually stay live-bound.
  // ---------------------------------------------------------------------
  PwObjectTracker {
    objects: Pipewire.defaultAudioSink ? [Pipewire.defaultAudioSink] : []
  }

  function connectedNetworkDevice() {
    const devices = Networking.devices.values;
    for (let i = 0; i < devices.length; i++) if (devices[i].connected) return devices[i];
    return null;
  }
  function connectedNetwork(device) {
    if (!device) return null;
    const nets = device.networks.values;
    for (let i = 0; i < nets.length; i++) if (nets[i].connected) return nets[i];
    return null;
  }

  // One bar per connected monitor, not just whichever one quickshell
  // treats as primary.
  Variants {
    model: Quickshell.screens

    PanelWindow {
      id: bar
      property var modelData
      screen: modelData
      anchors { left: true; right: true; top: true }
      implicitHeight: 50
      color: "transparent"

    // ---------------- clock island ----------------
    WrapperRectangle {
      id: clockIsland
      anchors.left: parent.left
      anchors.leftMargin: 14
      anchors.verticalCenter: parent.verticalCenter
      margin: 16
      implicitHeight: root.islandHeight
      radius: 16
      color: root.islandBg

      // WrapperRectangle manages (and positions) its direct child itself -
      // putting anchors on that child directly conflicts with it (per
      // WrapperRectangle's own docs), which is what was throwing the clock
      // text's vertical centering off compared to the other islands. A
      // single-item Row as the direct child sidesteps that: the Row is
      // wrapper-managed with no anchors of its own, and Chip's anchor
      // targets the Row instead, which is fine.
      Row {
        Chip {
          label: Qt.formatDateTime(new Date(), "ddd dd MMM  HH:mm")

          Timer {
            interval: 1000
            running: true
            repeat: true
            onTriggered: parent.label = Qt.formatDateTime(new Date(), "ddd dd MMM  HH:mm")
          }
        }
      }
    }

    // ---------------- tray island ----------------
    WrapperRectangle {
      anchors.left: clockIsland.right
      anchors.leftMargin: 14
      anchors.verticalCenter: parent.verticalCenter
      margin: 16
      implicitHeight: root.islandHeight
      radius: 16
      color: root.islandBg

      Row {
        spacing: 14
        Repeater {
          model: SystemTray.items
          delegate: Rectangle {
            id: trayDelegate
            width: 30
            height: 30
            radius: 8
            color: root.chipBg

            Image {
              anchors.centerIn: parent
              width: 18
              height: 18
              source: modelData.icon
            }

            // Anchored to this specific icon (not raw mouse coordinates,
            // which were relative to the icon, not the window - the menu
            // was opening at the bar's top-left every time).
            QsMenuAnchor {
              id: trayMenuAnchor
              anchor {
                item: trayDelegate
                gravity: Edges.Bottom | Edges.Right
                edges: Edges.Bottom | Edges.Right
              }
            }

            MouseArea {
              anchors.fill: parent
              acceptedButtons: Qt.LeftButton | Qt.RightButton
              onClicked: (mouse) => {
                if (mouse.button === Qt.RightButton) {
                  if (modelData.menu) {
                    trayMenuAnchor.menu = modelData.menu;
                    trayMenuAnchor.open();
                  } else {
                    modelData.secondaryActivate();
                  }
                } else {
                  modelData.activate();
                }
              }
            }
          }
        }
      }
    }

    // ---------------- workspaces island (the true bar-center anchor) ----------------
    WrapperRectangle {
      id: workspacesIsland
      anchors.horizontalCenter: parent.horizontalCenter
      anchors.verticalCenter: parent.verticalCenter
      margin: 16
      implicitHeight: root.islandHeight
      radius: 16
      color: root.islandBg

      Row {
        spacing: 10

        Repeater {
          model: mergedWorkspaceIds()
          delegate: Rectangle {
            readonly property int wsId: modelData
            readonly property bool focused: wsId === focusedWorkspaceId()
            width: 42
            height: 36
            radius: 12
            color: focused ? root.accentColor : root.chipBg

            Text {
              anchors.centerIn: parent
              text: workspaceIcon(wsId)
              font.pixelSize: 20
              color: focused ? "#ffffff" : root.mutedTextColor
            }

            MouseArea {
              anchors.fill: parent
              onClicked: focusWorkspace(wsId)
            }
          }
        }
      }
    }

    // ---------------- notification island - separate from workspaces so it ----------------
    // ---------------- doesn't visually read as just another workspace pill ----------------
    WrapperRectangle {
      anchors.right: workspacesIsland.left
      anchors.rightMargin: 14
      anchors.verticalCenter: parent.verticalCenter
      margin: 16
      implicitHeight: root.islandHeight
      radius: 16
      color: root.islandBg

      Row {
        Rectangle {
          width: 34
          height: 34
          radius: 10
          color: root.chipBg

          Text {
            anchors.centerIn: parent
            text: notifIcon
            color: root.textColor
            font.pixelSize: 18
          }

          MouseArea {
            anchors.fill: parent
            acceptedButtons: Qt.LeftButton | Qt.RightButton
            onClicked: (mouse) => {
              if (mouse.button === Qt.RightButton) notifDismiss.running = true;
              else notifToggle.running = true;
            }
          }
        }
      }
    }

    // ---------------- power island ----------------
    WrapperRectangle {
      id: powerIsland
      anchors.left: workspacesIsland.right
      anchors.leftMargin: 14
      anchors.verticalCenter: parent.verticalCenter
      margin: 16
      implicitHeight: root.islandHeight
      radius: 16
      color: root.islandBg

      Row {
        Rectangle {
          width: 34
          height: 34
          radius: 10
          color: root.chipBg

          Text {
            anchors.centerIn: parent
            text: "⏻"
            color: root.textColor
            font.pixelSize: 16
          }

          MouseArea {
            anchors.fill: parent
            onClicked: sessionScreen.toggle()
          }
        }
      }
    }

    // ---------------- tasks island: "Tasks: N" launcher/status ----------------
    WrapperRectangle {
      anchors.left: powerIsland.right
      anchors.leftMargin: 14
      anchors.verticalCenter: parent.verticalCenter
      margin: 16
      implicitHeight: root.islandHeight
      radius: 16
      color: root.islandBg

      // Chip as WrapperRectangle's direct child would fight the wrapper's
      // own positioning (same issue the clock island had) - the MouseArea's
      // hit area ended up not lining up with the rendered text, so clicks
      // landed nowhere. Single-item Row sidesteps it.
      Row {
        Chip {
          label: "Tasks: " + activeTaskCount()

          MouseArea {
            anchors.fill: parent
            onClicked: taskPickerProc.running = true
          }
        }
      }
    }

    // ---------------- right island: network, audio, cpu, memory, battery ----------------
    WrapperRectangle {
      anchors.right: parent.right
      anchors.rightMargin: 14
      anchors.verticalCenter: parent.verticalCenter
      margin: 16
      implicitHeight: root.islandHeight
      radius: 16
      color: root.islandBg

      Row {
        spacing: 20

        Chip {
          readonly property var device: connectedNetworkDevice()
          readonly property var net: connectedNetwork(device)
          label: {
            if (!device) return " Disconnected";
            if (device.type === DeviceType.Wifi) return "󰤨 " + (net ? net.name : device.name);
            return "󰅢 " + device.name;
          }
        }

        Chip {
          id: audioChip
          readonly property var sink: Pipewire.defaultAudioSink
          label: {
            if (!sink || !sink.audio) return "--";
            const pct = Math.round(sink.audio.volume * 100);
            return (sink.audio.muted ? "󰖁 " : " ") + pct + "%";
          }

          MouseArea {
            anchors.fill: parent
            onClicked: {
              const sink = Pipewire.defaultAudioSink;
              if (sink && sink.audio) sink.audio.muted = !sink.audio.muted;
            }
            onWheel: (wheel) => {
              const sink = Pipewire.defaultAudioSink;
              if (!sink || !sink.audio) return;
              const step = 0.05;
              const delta = wheel.angleDelta.y > 0 ? step : -step;
              sink.audio.volume = Math.max(0, Math.min(1, sink.audio.volume + delta));
            }
          }
        }

        Chip {
          label: " " + cpuUsage + "%"
        }

        Chip {
          label: " " + memUsedGb.toFixed(1) + "G"
        }

        Chip {
          readonly property var battery: UPower.displayDevice
          visible: battery && battery.isPresent
          label: {
            if (!battery || !battery.isPresent) return "";
            const icons = ["󰂎 ", "󰁼 ", "󰁿 ", "󰂁 ", "󰁹 "];
            const pct = Math.round(battery.percentage * 100);
            const tier = Math.max(0, Math.min(icons.length - 1, Math.floor(pct / 25)));
            const charging = battery.state === UPowerDeviceState.Charging;
            return icons[tier] + (charging ? "󱐋 " : "") + pct + "%";
          }
        }
      }
    }
    }
  }
}
